spring:
  datasource:
    username: postgres
    password: Ahmed@2252300
    url: jdbc:postgresql://localhost:5432/medica
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true