spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/medica
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  stripe:
    api-key: k_test_51PVCfoD7kDMB0EVHY3pGPb8X8oysHRvxDj8n4SpZ8A8wsgtsDjMtL93gFJHV66mMQybBP3bqHZKi8QQCa8KGpDcN00kSmMMyQL # Replace with your secret key
    webhook-secret: whsec_YourWebhookSecret # Replace with your webhook secret


  mail:
    host: sandbox.smtp.mailtrap.io
    username: af7756b39fe8eb
    port: 587
    password: e3a9e4bc120f82
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  elasticsearch:
    uris: http://localhost:9200



jwt:
  secret:
    key: gzQz0ZfvxCSk5erqGERapQmQJ43mmka5Ub1kyijKYenPyBy18tZrMeUOh/DAjtNC
    expiration-time: 86400000 # 1 day
    refresh-token:
      expiration-time: 604800000 # 1 week
