spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/medica
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret:
    key: gzQz0ZfvxCSk5erqGERapQmQJ43mmka5Ub1kyijKYenPyBy18tZrMeUOh/DAjtNC
    expiration-time: 900000 # 15 minutes
    refresh-token:
      expiration-time: 86400000 # 1 day

  mail:
    host: smtp.gmail.com
    port: 587
    username: os.omarsalah@gmail.com
    password: urzmokjzfhbyxzrl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
