spring:
  datasource:
    username: postgres
    password: Ahmed@2252300
    url: jdbc:postgresql://localhost:5432/medica
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    username: os.omarsalah@gmail.com
    port: 587
    password: urzmokjzfhbyxzrl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  elasticsearch:
    uris: http://localhost:9200



jwt:
  secret:
    key: gzQz0ZfvxCSk5erqGERapQmQJ43mmka5Ub1kyijKYenPyBy18tZrMeUOh/DAjtNC
    expiration-time: 86400000 # 1 day
    refresh-token:
      expiration-time: 604800000 # 1 week
