export const mapPatientHistDtoToPatientHist = (patientHistDto) => (
    {
        "hasPhysDiuresis": patientHistDto.hasPhysDiuresis,
        "hasPhysDiet": patientHistDto.hasPhysDiet,
        "hasPhysDrugs": patientHistDto.hasPhysDrugs,
        "hasPhysAlvo": patientHistDto.hasPhysAlvo,
        "hasPhysPregnancies": patientHistDto.hasPhysPregnancies,
        "hasPhysAlcohol": patientHistDto.hasPhysAlcohol,
        "hasPhysSmoke": patientHistDto.hasPhysSmoke,
        "hasPhysPeriod": patientHistDto.hasPhysPeriod,
        "hasPastCardio": patientHistDto.hasPastCardio,
        "hasPastCancer": patientHistDto.hasPastCancer,
        "hasPastHyp": patientHistDto.hasPastHyp,
        "hasPastNothing": patientHistDto.hasPastNothing,
        "hasPastInfect": patientHistDto.hasPastInfect,
        "hasPastOrto": patientHistDto.hasPastOrto,
        "hasPastDrugAdd": patientHistDto.hasPastDrugAdd,
        "hasPastEndo": patientHistDto.hasPastEndo,
        "hasPastResp": patientHistDto.hasPastResp,
        "pastNotes": patientHistDto.pastNotes,
        "hasFamCardio": patientHistDto.hasFamCardio,
        "hasFamCancer": patientHistDto.hasFamCancer,
        "hasFamHyp": patientHistDto.hasFamHyp,
        "hasFamNothing": patientHistDto.hasFamNothing,
        "hasFamInfect": patientHistDto.hasFamInfect,
        "hasFamOrto": patientHistDto.hasFamOrto,
        "hasFamDrugAdd": patientHistDto.hasFamDrugAdd,
        "hasFamEndo": patientHistDto.hasFamEndo,
        "hasFamResp": patientHistDto.hasFamResp,
        "familyNotes": patientHistDto.familyNotes,
        "allergies": patientHistDto.allergies,
        "usualMedic": patientHistDto.usualMedic,
        "surgeries": patientHistDto.surgeries,
        "additionalNote": patientHistDto.additionalNote,
        "notes": patientHistDto.notes,
    }
)